name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  
  build:
   
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -t pmpoyi1987/my-resume

      - name: Push image
        run: |
       docker login -u pmpoyi1987 -p ${{secrets.REGISTRY_PASS}}
       docker push pmpoyi1987/my-resume 
