name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker images
        run: |
          docker build -t ${{ secrets.REGISTRY_USER }}/my-resume:${{ github.run_number }} .
          docker build -t ${{ secrets.REGISTRY_USER }}/my-resume .

      - name: Log in to Docker registry
        run: |
          docker login -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_PASS }}

      - name: Push Docker images
        run: |
          docker push ${{ secrets.REGISTRY_USER }}/my-resume:${{ github.run_number }}
          docker push ${{ secrets.REGISTRY_USER }}/my-resume
