
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
jobs:
  
  build:
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -t pmpoyi2024/my-resume .

      - name: Push image
        run: |
            docker login -u pmpoyi2024 -p ${{secrets.REGISTRY_PASS}}
            docker push pmpoyi2024/my-resume
